package tests.base;

public enum Constants {

    suiteTypeAll("Use a single repository for all cases (recommended)"),
    suiteTypeBaseline("Use a single repository with baseline support"),
    suiteTypeManage("Use multiple test suites to manage cases"),
    ProjectAddTabAccess("projects-tabs-access"),
    ProjectAddTabDefects("projects-tabs-defects"),
    ProjectAddTabReferences("projects-tabs-references"),
    ProjectAddTabUserVariables("users-fields-fields"),
    ProjectAddDefaultAccessGlobal("Global Role"),
    ProjectAddDefaultAccessRead("Read-only"),
    ProjectAddDefaultAccessTester("Tester"),
    ProjectAddDefaultAccessDesigner("Designer"),
    ProjectAddDefaultAccessLead("Lead"),
    DropDownUserMenu("navigation-user"),
    DropDownUserMenuOptionLogOut("Logout"),
    DropDownProjectGlobalAccess("access"),
    DropDownProjectDefectPlugin("Defect plugin"),
    DropDownProjectReferencePlugin("Reference plugin"),
    InputDefectViewUrl("defect_id_url"),
    InputDefectAddUrl("defect_add_url"),
    InputReferenceViewUrl("reference_id_url"),
    InputReferenceAddUrl("reference_add_url"),
    InputVariableLabel("userFieldLabel"),
    InputVariableDescription("userFieldDesc"),
    InputVariableSystemName("userFieldName"),
    DefectPluginAsana("Asana"),
    DefectPluginAssembla("Assembla"),
    DefectPluginAxosoftOnTimeREST("Axosoft / OnTime REST"),
    DefectPluginAxosoftOnTimeSOAPOldVersions("Axosoft / OnTime SOAP (old versions)"),
    DefectPluginAxosoftV17REST("Axosoft_v17_REST"),
    DefectPluginAzureDevOpsCLOUD("Azure_DevOps_CLOUD"),
    DefectPluginAzureDevOpsSERVER("Azure_DevOps_SERVER"),
    DefectPluginBitbucket("Bitbucket"),
    DefectPluginBugzilla("Bugzilla"),
    DefectPluginBugzillaREST("Bugzilla_REST"),
    DefectPluginBugzilla_XMLRPC("Bugzilla_XMLRPC"),
    DefectPluginEmail("Email"),
    DefectPluginGitHub("GitHub"),
    DefectPluginGitLab("GitLab"),
    DefectPluginJIRACloud("JIRA Cloud"),
    DefectPluginJIRARESTJIRAServer5_7AndLater("JIRA REST (JIRA Server 5.x, 6.x, 7.x and later)"),
    DefectPluginJIRASOAPJIRAServer3_4("JIRA SOAP (JIRA Server 3.x, 4.x)"),
    DefectPluginLighthouse("Lighthouse"),
    DefectPluginMantisREST("Mantis_REST"),
    DefectPluginMantisSOAP("Mantis_SOAP"),
    DefectPluginManuscript("Manuscript"),
    DefectPluginPivotalTracker("PivotalTracker"),
    DefectPluginRally("Rally"),
    DefectPluginRedmine("Redmine"),
    DefectPluginSample("Sample"),
    DefectPluginTrac("Trac"),
    DefectPluginTrello("Trello"),
    DefectPluginVersionOne("VersionOne"),
    DefectPluginYouTrack("YouTrack"),
    DefectPluginYouTrack20182("YouTrack20182"),
    DefectPluginYouTrack20184("YouTrack20184"),
    NewUserThemeModern("Modern"),
    NewUserThemeDark("Dark"),
    NewUserThemeClassic("Classic"),
    DropDownSelectType("userFieldType"),
    DefectPluginYouTrack20191("YouTrack20191"),
    AdministrationTabLocator("navigation-admin"),
    DashboardTabLocator("navigation-dashboard"),
    ProjectListDashboardLocator("//a[contains(text(),'%s')]"),
    ProjectInListLocator("//a[contains(text(),\"%s\")]"),
    ProjectNameLocator(".page_title"),
    ProjectAnnouncementsLocator(".markdown >p"),
    ButtonReturnToDashboardLocator("navigation-dashboard-top"),
    ListOfCompletedProjectsLocator("//div[contains(@id,'completed')]//a[contains(text(),'%s')]"),
    ListOfInProgressProjectsLocator("//div[contains(@class,'flex-projects-row')]//a[contains(text(),'%s')]"),
    UserNameLocator(".navigation-username"),
    typeOfInvite("Manually specify password (no invitation is sent)"),
    UserVariableTypeString("String"),
    UserVariableTypePassword("Password"),
    CustomizationTabLocator(".tab-header"),
    DataManagementTabLocator(".tab-storage"),
    IntegrationTabLocator(".button-edit"),
    NewUserSwitchTabLocator("//div/a[contains(text(),'%s')]"),
    NewUserInputName("name"),
    NewUserInputEmail("email"),
    ButtonEdit(".button-edit"),
    NewUserEmailNotificationLocator("//strong[contains(text(),'Enable email notifications')]//ancestor::div[contai" +
            "ns(@class,'checkbox')]//input"),
    DropDownSelectLanguage("language"),
    DropDownSelectTheme("theme"),
    DropDownSelectRole("role_id"),
    NewUserNoInvitationIsSentLocator("invite_no"),
    NewUserSetPasswordLocator("input[name = 'password']"),
    NewUserConfirmPasswordLocator("input[name = 'confirm']"),
    NewUserTabAccess("Access"),
    NewUserTabProjects("Projects"),
    NewUserTabProjectProjectNameLocator("//a[contains(text(),'%s')]//ancestor::tr//a[contains(@class,'nolink')]"),
    NewUserTabProjectProjectAccessLocator("//div[contains(@id,'userProjectAccessDropdown')]//a[contains(text(),'%s')]"),
    NewUserCheckboxIsActive("This user is active"),
    NewUserCheckboxIsAdministrator("This user is an administrator"),
    AdministrationTabOverViewTabLocator(".storage-box-title"),
    AdministrationTabProjectTabButtonAddLocator(".button-add"),
    AdministrationTabSiteSettingTabTopMenuLocator(".tab-site-settings"),
    AdministrationTabUserAndRolesTabSearchFieldLocator(".toolbar-search-box"),
    AdministrationTabUserAndRolesTabButtonAddUserLocator("//a[contains(text(),'Add User')]"),
    AdministrationTabOpenProjectTabLocator("navigation-sub-projects"),
    AdministrationTabProjectTabDeleteProjectLocator(" //a[contains(@onclick,'%s')]"),
    AdministrationTabProjectTabDeleteProjectConfirmWindowButtonOkLocator(".ui-dialog  .button-ok"),
    AdministrationTabProjectTabDeleteProjectMessageSuccessLocator(".message-success"),
    AdministrationTabOpenUserAndRoleTabLocator("navigation-sub-users"),
    AdministrationTabOpenOverViewTabLocator("navigation-sub-overview"),
    AdministrationTabOpenCustomizationsTabLocator("navigation-sub-customization"),
    AdministrationTabOpenIntegrationTabLocator("navigation-sub-integration"),
    AdministrationTabOpenDataManagementTabLocator("navigation-sub-subscription"),
    AdministrationTabOpenSiteSettingsTabLocator("navigation-sub-sitesettings"),
    HomePageButtonNewProjectLocator(".sidebar-button"),
    FieldName("name"),
    FieldAnnouncement("announcement"),
    CheckBoxAnnouncement("show_announcement"),
    CheckBoxUseASingleRepositoryWithBaselineSupportLocator("Use a single repository with baseline support"),
    CheckBoxUseMultipleTestSuitesToManageCasesLocator("Use multiple test suites to manage cases"),
    FieldDefectViewURLLocator("//label[contains(text(),'Defect View Url')]/ancestor::div[contains(@class," +
            "'form-group')]/input"),
    FieldDefectAddURLLocator("//label[contains(text(),'Defect Add Url')]/ancestor::div[contains(@class," +
            "'form-group')]/input"),
    DefectPluginInputLocator("//div[contains(@id,'defect_plugin_chzn')]//span"),
    FieldReferenceViewURLLocator("//label[contains(text(),'Reference View Url')]/ancestor::div[contains(@class," +
            "'form-group')]/input"),
    FieldReferenceAddURLLocator("//label[contains(text(),'Reference Add Url')]/ancestor::div[contains(@class," +
            "'form-group')]/input"),
    ReferencePluginInputLocator("//div[contains(@id,'reference_plugin_chzn')]//span"),
    ButtonAddUserVariableLocator("//a[contains(text(),'Add User Variable')]"),
    SwitchTabLocator("//a[@id = '%s' and contains(@class,'current')]"),
    ButtonOkLocator("userFieldSubmit"),
    ButtonAcceptAdd("accept");

    public final String value;

    Constants(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
