package tests.base;

//TODO rename to Constants
public enum Enum {
    suiteTypeAll("Use a single repository for all cases (recommended)"),
    suiteTypeBaseline("Use a single repository with baseline support"),
    suiteTypeManage("Use multiple test suites to manage cases"),
    ProjectAddTabAccess("projects-tabs-access"),
    ProjectAddTabDefects("projects-tabs-defects"),
    ProjectAddTabReferences("projects-tabs-references"),
    ProjectAddTabUserVariables("users-fields-fields"),
    ProjectAddDefaultAccessGlobal("Global Role"),
    ProjectAddDefaultAccessNo("No Access"),
    ProjectAddDefaultAccessRead("Read-only"),
    ProjectAddDefaultAccessTester("Tester"),
    ProjectAddDefaultAccessDesigner("Designer"),
    ProjectAddDefaultAccessLead("Lead"),
    DropDownHelpAndFeedBack("Navigation"),
    DropDownUserMenu("User dropdown"),
    DropDownUserMenuOptionLogOut("Logout"),
    DropDownProjectGlobalAccess("Project access"),
    DropDownProjectDefectPlugin("Defect plugin"),
    DropDownProjectReferencePlugin("Reference plugin"),
    InputDefectViewUrl("defect_id_url"),
    InputDefectAddUrl("defect_add_url"),
    InputReferenceViewUrl("reference_id_url"),
    InputReferenceAddUrl("reference_add_url"),
    InputVariableLabel("userFieldLabel"),
    InputVariableDescription("userFieldDesc"),
    InputVariableSystemName("userFieldName"),
    DefectPluginAsana("Asana"),
    DefectPluginAssembla("Assembla"),
    DefectPluginAxosoftOnTimeREST("Axosoft / OnTime REST"),
    DefectPluginAxosoftOnTimeSOAPOldVersions("Axosoft / OnTime SOAP (old versions)"),
    DefectPluginAxosoftV17REST("Axosoft_v17_REST"),
    DefectPluginAzureDevOpsCLOUD("Azure_DevOps_CLOUD"),
    DefectPluginAzureDevOpsSERVER("Azure_DevOps_SERVER"),
    DefectPluginBitbucket("Bitbucket"),
    DefectPluginBugzilla("Bugzilla"),
    DefectPluginBugzillaREST("Bugzilla_REST"),
    DefectPluginBugzilla_XMLRPC("Bugzilla_XMLRPC"),
    DefectPluginEmail("Email"),
    DefectPluginGitHub("GitHub"),
    DefectPluginGitLab("GitLab"),
    DefectPluginJIRACloud("JIRA Cloud"),
    DefectPluginJIRARESTJIRAServer5_7AndLater("JIRA REST (JIRA Server 5.x, 6.x, 7.x and later)"),
    DefectPluginJIRASOAPJIRAServer3_4("JIRA SOAP (JIRA Server 3.x, 4.x)"),
    DefectPluginLighthouse("Lighthouse"),
    DefectPluginMantisREST("Mantis_REST"),
    DefectPluginMantisSOAP("Mantis_SOAP"),
    DefectPluginManuscript("Manuscript"),
    DefectPluginPivotalTracker("PivotalTracker"),
    DefectPluginRally("Rally"),
    DefectPluginRedmine("Redmine"),
    DefectPluginSample("Sample"),
    DefectPluginTrac("Trac"),
    DefectPluginTrello("Trello"),
    DefectPluginVersionOne("VersionOne"),
    DefectPluginYouTrack("YouTrack"),
    DefectPluginYouTrack20182("YouTrack20182"),
    DefectPluginYouTrack20184("YouTrack20184"),
    NewUserThemeModern("Modern"),
    NewUserThemeDark("Dark"),
    NewUserThemeClassic("Classic"),
    DefectPluginYouTrack20191("YouTrack20191"),
    BLOG_LOCATOR("div> a[href^=\"http://blog.gurock.com/\"]"),
    TWITTER_LOCATOR("div> a[href^=\"http://twitter.com/testrail\"]"),
    NEWSLETTER_LOCATOR("div> a[href^=\"https://secure.gurock.com/customers/testrail/newsletter?email=%s\"]"),
    AdministrationTabLocator("navigation-admin"),
    DashboardTabLocator("navigation-dashboard"),
    ProjectInListLocator("//a[contains(text(),\"%s\")]"),
    ProjectNameLocator(".page_title"),
    ProjectAnnouncementsLocator(".markdown >p"),
    ButtonReturnToDashboardLocator("navigation-dashboard-top"),
    ListOfCompletedProjectsLocator("//div[contains(@id,'completed')]//a[contains(text(),'%s')]"),
    ListOfInProgressProjectsLocator("//div[contains(@class,'flex-projects-row')]//a[contains(text(),'%s')]"),
    UserNameLocator(".navigation-username"),
    typeOfInvite("Manually specify password (no invitation is sent)"),
    UserVariableTypeString("String"),
    UserVariableTypePassword("Password"),
    CustomizationTabLocator(".tab-header"),
    DataManagementTabLocator(".tab-storage"),
    IntegrationTabLocator(".button-edit"),
    NewUserSwitchTabLocator("//div/a[contains(text(),'%s')]"),
    NewUserInputName("name"),
    NewUserInputEmail("email"),
    NewUserEmailNotificationLocator("//strong[contains(text(),'Enable email notifications')]//ancestor::div[contai" +
            "ns(@class,'checkbox')]//input"),
    DropDownLanguage("Language"),
    DropDownTheme("Theme"),
    NewUserNoInvitationIsSentLocator("invite_no"),
    NewUserSetPasswordLocator("input[name = 'password']"),
    NewUserConfirmPasswordLocator("input[name = 'confirm']"),
    NewUserTabAccess("Access"),
    NewUserTabProjects("Projects"),
    NewUserTabProjectProjectNameLocator("//a[contains(text(),'%s')]//ancestor::tr//a[contains(@class,'nolink')]"),
    NewUserTabProjectProjectAccessLocator("//div[contains(@id,'userProjectAccessDropdown')]//a[contains(text(),'%s')]"),
    NewUserDropDownRole("Role"),
    NewUserCheckboxIsActive("This user is active"),
    NewUserCheckboxIsAdministrator("This user is an administrator"),
    AdministrationTabOverViewTabLocator(".storage-box-title"),
    AdministrationTabProjectTabButtonAddLocator(".button-add"),
    AdministrationTabSiteSettingTabTopMenuLocator(".tab-site-settings"),
    AdministrationTabUserAndRolesTabSearchFieldLocator(".toolbar-search-box"),
    AdministrationTabUserAndRolesTabButtonAddUserLocator("//a[contains(text(),'Add User')]"),
    AdministrationTabOpenProjectTabLocator("navigation-sub-projects"),
    AdministrationTabProjectTabDeleteProjectLocator(" //a[contains(@onclick,'%s')]"),
    AdministrationTabProjectTabDeleteProjectConfirmWindowButtonOkLocator(".ui-dialog  .button-ok"),
    AdministrationTabProjectTabDeleteProjectMessageSuccessLocator(".message-success"),

    AdministrationTabOpenUserAndRoleTabLocator("#navigation-sub-users"),
    AdministrationTabOpenOverViewTabLocator("navigation-sub-overview"),
    AdministrationTabOpenCustomizationsTabLocator("navigation-sub-customization"),
    AdministrationTabOpenIntegrationTabLocator("navigation-sub-integration"),
    AdministrationTabOpenDataManagementTabLocator("navigation-sub-subscription"),
    AdministrationTabOpenSiteSettingsTabLocator("navigation-sub-sitesettings"),
    BlogPageIsOpenedLocator("div >[type=\"submit\"]"),
    HomePageButtonNewProjectLocator(".sidebar-button"),

    NewUserButtonAddLocator("accept");


    public final String value;

    Enum(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
